### ISSUE TITLE
Git ignore npm & webstorm

### ISSUE THREAD

**Issue by valentindoche** [Student-Gaming-Network/website#13]
Folder node_modules and npm depencies want commit.

**Comment by TheHerobrine** [comment]
@valentindoche Comme je disais dans la PR, il faut pas faire `npm install` dans le dossier racine, mais dans les dossier `client` et `backend` 😉

**Comment by valentindoche** [comment]
C'est ce que j'ai fait et il m'a quand même demandé de commit/add les dossiers quand j'ai changé le .git ignore tous était bon je vais essayer a nouveau voir si j'ai mal fait un truc

**Comment by valentindoche** [comment]
En effet je confirme je n'ai plus ce problème bizarre je close
